[package]
name = "cli"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
thiserror = "2.0.16"
log = "0.4.27"
env_logger = "0.11.8"
indicatif = "0.18.0"
console = "0.16.0"
indicatif-log-bridge = "0.2.3"
rust-embed = { version = "8.7.2", features = ["debug-embed"] }
serde_json = { version = "1.0.143", features = ["default"] }
serde = { version = "1.0.219", features = ["derive"] }
cfg-if = "1.0.3"

[[bin]]
name = "lumina"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
